export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGIN_USER_ERROR";

export const FETCH_RANDOM_PENDING = "FETCH_RANDOM_PENDING";
export const FETCH_RANDOM_SUCCESS = "FETCH_RANDOM_SUCCESS";
export const FETCH_RANDOM_ERROR = "FETCH_RANDOM_ERROR";

export const FETCH_CONTACTS_PENDING = "FETCH_CONTACTS_PENDING";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const FETCH_CONTACTS_ERROR = "FETCH_CONTACTS_ERROR";
